// Generated by dia2code
#ifndef STATE__ELEMENTTAB__H
#define STATE__ELEMENTTAB__H

#include <vector>
#include <memory>
#include <stdlib.h>
#include <string>

namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class ElementTab - 
  class ElementTab {
    // Associations
    // Attributes
  private:
    std::vector<std::unique_ptr<Element>> m_board;
    size_t m_width;
    size_t m_height;
    // Operations
  public:
    ElementTab (size_t width = 5, size_t height = 4);
    size_t getWidth ();
    size_t getHeight ();
    Element* getElement (int i, int j = 0);
    void setElement (int i, int j, Element* e);
    void resize (size_t width, size_t height);
    void load (std::string& file);
    Element& operator() (int i, int j = 0);
    void add (Element* e);
    // Setters and Getters
  };

};

#endif
