// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {

  /// class Element - 
  class Element {
    // Attributes
  protected:
    int m_x;
    int m_y;
    // Operations
  public:
    Element ();
    ~Element ();
    virtual bool isStatic () = 0;
    void setx (int x);
    int getx ();
    int gety ();
    void sety (int y);
    // Setters and Getters
  };

};

#endif
