// Generated by dia2code
#ifndef STATE__ELEMENTTAB__H
#define STATE__ELEMENTTAB__H

#include <vector>
#include <memory>
#include <stdlib.h>

namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class ElementTab - 
  class ElementTab {
    // Associations
    // Attributes
  private:
    std::vector<std::unique_ptr<Element>> board;
    size_t width;
    size_t height;
    // Operations
  public:
    ElementTab (size_t width = 5, size_t height = 5);
    size_t const getWidth ();
    size_t const getHeight ();
    // Setters and Getters
  };

};

#endif
