// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H

#include <string>

namespace state {
  class ElementTab;
}

#include "ElementTab.h"

namespace state {

  /// class State - 
  class State {
    // Associations
    // Attributes
  private:
    ElementTab m_teamBoard;
    ElementTab m_territoryBoard;
    std::string m_player     = "player1";
    // Operations
  public:
    ElementTab& getTerritoryBoard ();
    ElementTab& getTeamBoard ();
    std::string getPlayer ();
    void setPlayer (std::string player);
    // Setters and Getters
  };

};

#endif
