// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H


namespace state {
  class ElementTab;
}

#include "ElementTab.h"
#include "TeamStatus.h"

namespace state {

  /// class State - 
  class State {
    // Associations
    // Attributes
  private:
    ElementTab m_teamBoard;
    ElementTab m_territoryBoard;
    TeamStatus m_player     = DRAGONS;
    // Operations
  public:
    ElementTab& getTerritoryBoard ();
    ElementTab& getTeamBoard ();
    TeamStatus getPlayer ();
    void setPlayer (TeamStatus player);
    bool isGameOver ();
    // Setters and Getters
  };

};

#endif
