// Generated by dia2code
#ifndef STATE__TEAM__H
#define STATE__TEAM__H


namespace state {
  class Element;
}

#include "TeamStatus.h"
#include "Element.h"

namespace state {

  /// class Team - 
  class Team : public state::Element {
    // Associations
    // Attributes
  private:
    int nbCreatures     = 1;
    TeamStatus const teamStatus;
    // Operations
  public:
    int getNbCreatures ();
    void setNbCreatures (int nbCreatures = 1);
    TeamStatus const getTeamStatus ();
    TypeId const getTypeId ();
    bool const isStatic ();
    Team (TeamStatus id = DRAGONS);
    // Setters and Getters
  };

};

#endif
