// Generated by dia2code
#ifndef STATE__TERRITORYTYPEID__H
#define STATE__TERRITORYTYPEID__H


namespace state {

  enum TerritoryTypeId {
    ACCESSABLE     = 1,
    IMPOSSIBLE     = 2
  };

};

#endif
