// Generated by dia2code
#ifndef STATE__TERRITORYSTATUS__H
#define STATE__TERRITORYSTATUS__H


namespace state {

  enum TerritoryStatus {
    UNICORNS_T     = 1,
    DRAGONS_T     = 2,
    IMPOSSIBLE     = 3
  };

};

#endif
