// Generated by dia2code
#ifndef STATE__TERRITORYSTATUS__H
#define STATE__TERRITORYSTATUS__H


namespace state {

  enum TerritoryStatus {
    ACCESSIBLE     = 1,
    IMPOSSIBLE     = 2
  };

};

#endif
