// Generated by dia2code
#ifndef RENDER__NUMBERTILESET__H
#define RENDER__NUMBERTILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"

namespace render {

  /// class NumberTileSet - 
  class NumberTileSet : public render::TileSet {
    // Attributes
  private:
    std::vector<Tile> m_numbers;
    // Operations
  public:
    NumberTileSet ();
    int getCellWidth ();
    int getCellHeight ();
    std::string getImageFile ();
    Tile& getCharTile (int c);
    // Setters and Getters
  };

};

#endif
