// Generated by dia2code
#ifndef RENDER__SURFACE__H
#define RENDER__SURFACE__H

#include <SFML/Graphics.hpp>
#include <string>

namespace sf {
  class Texture;
  class VertexArray;
};
namespace render {
  class Tile;
};
namespace sf {
  class Drawable;
  class Transformable;
}


namespace render {

  /// class Surface - 
  class Surface : public sf::Drawable, public sf::Transformable {
    // Associations
    // Attributes
  private:
    sf::Texture m_texture;
    sf::VertexArray m_hexas;
    // Operations
  public:
    void loadTexture (std::string& imageFile);
    void initHexas (int count);
    void setSpriteLocation (int i, int x, int y);
    void setSpriteTexture (int i, Tile& tex);
    void draw (sf::RenderTarget& target, sf::RenderStates states);
    // Setters and Getters
  };

};

#endif
