// Generated by dia2code
#ifndef RENDER__TERRITORYTILESET__H
#define RENDER__TERRITORYTILESET__H

#include <vector>
#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Element;
};
namespace render {
  class TileSet;
}

#include "Tile.h"
#include "TileSet.h"

namespace render {

  /// class TerritoryTileSet - 
  class TerritoryTileSet : public render::TileSet {
    // Attributes
  private:
    std::vector<Tile> m_territories;
    // Operations
  public:
    TerritoryTileSet ();
    int getCellWidth ();
    int getCellHeight ();
    std::string getImageFile ();
    Tile& getTile (state::Element& e);
    // Setters and Getters
  };

};

#endif
