// Generated by dia2code
#ifndef RENDER__TILESET__H
#define RENDER__TILESET__H

#include <string>

namespace render {
  class Tile;
};
namespace state {
  class Element;
}

#include "state/Element.h"
#include "Tile.h"

namespace render {

  /// class TileSet - 
  class TileSet {
    // Associations
    // Operations
  public:
    virtual ~TileSet ();
    virtual int getCellWidth () = 0;
    virtual int getCellHeight () = 0;
    virtual std::string getImageFile () = 0;
    virtual Tile& getTile (state::Element& e);
    Tile& getCharTile (char c);
    // Setters and Getters
  };

};

#endif
