// Generated by dia2code
#ifndef RENDER__TILE__H
#define RENDER__TILE__H


namespace render {

  /// class Tile - 
  class Tile {
    // Attributes
  protected:
    int x     = 0;
    int y     = 0;
    int m_width     = 120;
    int m_height     = 140;
    // Operations
  public:
    Tile ();
    Tile (int x, int y, int w, int h);
    int getx ();
    int gety ();
    int getHeight ();
    int getWidth ();
    // Setters and Getters
  };

};

#endif
