// Generated by dia2code
#ifndef AI__DEEPAI__H
#define AI__DEEPAI__H


namespace engine {
  class Engine;
};
namespace state {
  class State;
};
namespace ai {
  class AI;
}

#include "AI.h"

namespace ai {

  /// class DeepAI - 
  class DeepAI : public ai::AI {
    // Attributes
  private:
    int updatesCount     = 0;
  protected:
    int maxUpdates     = 5000;
    // Operations
  public:
    void run (engine::Engine& engine);
    DeepAI (state::State& state);
    // Setters and Getters
  };

};

#endif
