// Generated by dia2code
#ifndef ENGINE__ACTIONTYPEID__H
#define ENGINE__ACTIONTYPEID__H


namespace engine {

  enum ActionTypeId {
    RENFORTSACTION     = 0,
    WINACTION     = 1,
    LOOSEACTION     = 2
  };

};

#endif
