// Generated by dia2code
#ifndef ENGINE__ATTACKCOMMAND__H
#define ENGINE__ATTACKCOMMAND__H

#include <stack>
#include <memory>
#include <json/json.h>

namespace state {
  class State;
};
namespace engine {
  class Action;
  class AttackCommand;
  class Command;
  class LooseAction;
  class WinAction;
}

#include "CommandTypeId.h"
#include "Action.h"
#include "Command.h"
#include "LooseAction.h"
#include "WinAction.h"

namespace engine {

  /// class AttackCommand - 
  class AttackCommand : public engine::Command {
    // Attributes
  private:
    int m_iAtt;
    int m_jAtt;
    int m_iDef;
    int m_jDef;
    state::TeamStatus m_winner;
    // Operations
  public:
    AttackCommand (int iAtt, int jAtt, int iDef, int jDef, state::TeamStatus ts);
    CommandTypeId getTypeId () const;
    void attackWins (state::State& state, std::stack<std::shared_ptr<engine::Action>>& actions);
    void attackLooses (state::State& state, std::stack<std::shared_ptr<engine::Action>>& actions);
    int getIAtt ();
    void setIAtt (int iAtt);
    int getJAtt ();
    void setJAtt (int jAtt);
    int getIDef ();
    void setIDef (int iDef);
    int getJDef ();
    void setJDef (int jDef);
    void execute (state::State& state, std::stack<std::shared_ptr<engine::Action>>& actions);
    void serialize (Json::Value& out);
    static AttackCommand* deserialize (Json::Value& in);
    // Setters and Getters
  };

};

#endif
