// Generated by dia2code
#ifndef ENGINE__ATTACKACTION__H
#define ENGINE__ATTACKACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"
#include "state/State.h"

namespace engine {

  /// class AttackAction - 
  class AttackAction : public engine::Action {
    // Associations
    // Attributes
  private:
    int m_iAtt;
    int m_jAtt;
    int m_iDef;
    int m_jDef;
    int m_nbCreaturesAtt;
    int m_nbCreaturesDef;
    state::TeamStatus m_AttPlayerStatus;
    // Operations
  public:
    AttackAction (int iAtt, int jAtt, int iDef, int jDef, int nbCreaturesAtt, int nbCreaturesDef, state::TeamStatus attPlayerStatus);
    void apply (state::State& state);
    void undo (state::State& state);
    // Setters and Getters
  };

};

#endif
