// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H

#include <stack>
#include <memory>

namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "CommandTypeId.h"
#include "Action.h"
#include "state/State.h"

namespace engine {

  /// class Command - 
  class Command {
    // Attributes
  protected:
    CommandTypeId m_commandTypeId;
    // Operations
  public:
    virtual ~Command ();
    virtual CommandTypeId getTypeId () const;
    virtual void execute (state::State& state, std::stack<std::shared_ptr<Action>>& actions);
    // Setters and Getters
  };

};

#endif
