// Generated by dia2code
#ifndef ENGINE__COMMANDTYPEID__H
#define ENGINE__COMMANDTYPEID__H


namespace engine {

  enum CommandTypeId {
    RENFORTS     = 1,
    ATTACK     = 2,
    INIT     = 0
  };

};

#endif
