// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <vector>
#include <memory>

namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "state/State.h"
#include "Command.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Associations
    // Attributes
  private:
    state::State m_currentState;
    std::vector<std::unique_ptr<Command>> m_currentCommands;
    // Operations
  public:
    Engine ();
    ~Engine ();
    state::State& getState ();
    void addPassivCommands ();
    void addCommand (Command* cmd);
    void update ();
    // Setters and Getters
  };

};

#endif
