// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <vector>
#include <memory>
#include <stack>

namespace state {
  class State;
};
namespace engine {
  class Command;
  class Action;
}

#include "state/State.h"
#include "Action.h"
#include "Command.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Associations
    // Attributes
  private:
    state::State m_currentState;
    std::vector<std::unique_ptr<Command>> m_currentCommands;
    // Operations
  public:
    Engine ();
    ~Engine ();
    state::State& getState ();
    void addPassivCommands ();
    virtual void addCommand (Command* cmd);
    std::stack<std::shared_ptr<Action>> update ();
    void undo (std::stack<std::shared_ptr<Action>>& actions);
    void updateCommand (Command* command);
    // Setters and Getters
  };

};

#endif
