// Generated by dia2code
#ifndef ENGINE__GESTIONRENFORTS__H
#define ENGINE__GESTIONRENFORTS__H


namespace state {
  class State;
};
namespace engine {
  class Command;
}

#include "CommandTypeId.h"
#include "Command.h"

namespace engine {

  /// class GestionRenforts - 
  class GestionRenforts : public engine::Command {
    // Attributes
  protected:
    int m_renforts;
    // Operations
  public:
    GestionRenforts (int i);
    CommandTypeId getTypeId () const;
    void execute (state::State& state);
    int getRenforts ();
    void setRenforts (int renforts);
    // Setters and Getters
  };

};

#endif
