// Generated by dia2code
#ifndef ENGINE__LOOSEACTION__H
#define ENGINE__LOOSEACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "ActionTypeId.h"
#include "Action.h"

namespace engine {

  /// class LooseAction - 
  class LooseAction : public engine::Action {
    // Attributes
  private:
    int m_iAtt;
    int m_jAtt;
    int m_iDef;
    int m_jDef;
    int m_nbCreaturesAtt;
    int m_nbCreaturesDef;
    state::TeamStatus m_AttPlayerStatus ;
    // Operations
  public:
    LooseAction (int iAtt, int jAtt, int iDef, int jDef, int nbCreaturesAtt, int nbCreaturesDef, state::TeamStatus AttPlayerStatus);
    void apply (state::State& state);
    void undo (state::State& state);
    ActionTypeId getTypeId () const;
    // Setters and Getters
  };

};

#endif
