// Generated by dia2code
#ifndef ENGINE__RENFORTSACTION__H
#define ENGINE__RENFORTSACTION__H


namespace state {
  class State;
};
namespace engine {
  class Action;
}

#include "Action.h"
#include "state/State.h"

namespace engine {

  /// class RenfortsAction - 
  class RenfortsAction : public engine::Action {
    // Associations
    // Attributes
  private:
    state::TeamStatus m_playerStatus;
    // Operations
  public:
    RenfortsAction (state::TeamStatus playerStatus);
    void apply (state::State& state);
    void undo (state::State& state);
    // Setters and Getters
  };

};

#endif
