// Generated by dia2code
#ifndef SERVER__ENGINE_SERV__H
#define SERVER__ENGINE_SERV__H


namespace engine {
  class Command;
  class Engine;
}

#include "engine/Engine.h"

namespace server {

  /// class Engine_serv - 
  class Engine_serv : public engine::Engine {
    // Operations
  public:
    Engine_serv ();
    void addCommand (engine::Command* cmd);
    // Setters and Getters
  };

};

#endif
