// Generated by dia2code
#ifndef SERVER__GAMESERVICE__H
#define SERVER__GAMESERVICE__H

#include <json/json.h>

namespace server {
  class UserDB;
  class AbstractService;
}

#include "HttpStatus.h"
#include "AbstractService.h"

namespace server {

  /// class GameService - 
  class GameService : public server::AbstractService {
    // Attributes
  private:
    UserDB& game_m;
    // Operations
  public:
    GameService (UserDB& game);
    HttpStatus get (int id, Json::Value& out) const;
    // Setters and Getters
  };

};

#endif
