// Generated by dia2code
#ifndef SERVER__PLAYERSERVICE__H
#define SERVER__PLAYERSERVICE__H

#include <json/json.h>

namespace server {
  class Game;
  class AbstractService;
}

#include "HttpStatus.h"
#include "AbstractService.h"
#include "Game.h"

namespace server {

  /// class PlayerService - 
  class PlayerService : public server::AbstractService {
    // Associations
    // Attributes
  private:
    Game& game;
    // Operations
  public:
    PlayerService (Game& game);
    HttpStatus get (json::Value& out, int id) const;
    HttpStatus post (Json::Value& in, int id);
    HttpStatus put (Json::Value& out, Json::Value& in);
    Httpstatus remove (int id);
    // Setters and Getters
  };

};

#endif
