// Generated by dia2code
#ifndef SERVER__USER__H
#define SERVER__USER__H

#include <string>

namespace server {

  /// class User - 
  class User {
    // Attributes
  public:
    std::string m_name;
    int m_age;
    // Operations
  public:
    User (std::string name, int age);
    // Setters and Getters
  };

};

#endif
