// Generated by dia2code
#ifndef SERVER__USERDB__H
#define SERVER__USERDB__H

#include <map>
#include <memory>

namespace server {
  class User;
}

#include "User.h"

namespace server {

  /// class UserDB - 
  class UserDB {
    // Associations
    // Attributes
  protected:
    std::map<int,std::unique_ptr<User>> m_users;
    int m_idseq;
    // Operations
  public:
    UserDB ();
    const User* getUser (int id) const;
    int addUser (std::unique_ptr<User> user);
    void setUser (int id, std::unique_ptr<User> user);
    void removeUser (int id);
    int getSize ();
    // Setters and Getters
  };

};

#endif
