// Generated by dia2code
#ifndef __ENGINE__H
#define __ENGINE__H

#include "engine/Action.h"
#include "engine/CommandTypeId.h"
#include "engine/Command.h"
#include "engine/Engine.h"
#include "engine/AttackCommand.h"
#include "engine/GestionRenforts.h"
#include "engine/InitBasicState.h"
#include "engine/WinAction.h"
#include "engine/RenfortsAction.h"
#include "engine/LooseAction.h"
#endif
