// Generated by dia2code
#ifndef __RENDER__H
#define __RENDER__H

#include "render/Surface.h"
#include "render/Tile.h"
#include "render/TileSet.h"
#include "render/Layer.h"
#include "render/StateLayer.h"
#include "render/ElementTabLayer.h"
#include "render/TerritoryTileSet.h"
#include "render/NumberTileSet.h"
#include "render/TeamTileSet.h"
#endif
